# -*- coding: utf-8 -*-
"""Tugas  Mandiri 1 Praktikum algoritma dan Pemrograman

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MfzYUNqCU_zbEQ-Jdwi1zPUeXoMNC782

# Praktikum: Toko Dorayaki Doraemon

Program ini dirancang untuk mensimulasikan manajemen keuangan sederhana dari **Toko Dorayaki Doraemon**. Di dalam praktikum ini, kita akan mempelajari konsep-konsep dasar Python seperti:
1. Menerima masukan (*input*) dari pengguna dan menyimpannya dalam variabel.
2. Melakukan manipulasi string dasar (*string formatting* & *stripping*).
3. Melakukan perhitungan aritmatika sederhana (penjumlahan, perkalian, dan pengurangan).
4. Memperbaiki kesalahan kode (*error handling* / pembetulan tipe data).
"""

# Meminta masukan dari pengguna
nama_makanan = input("Masukkan nama makanan: ")
nama_karakter = input("Masukkan nama karakter: ")
kata_sifat = input("Masukkan kata sifat: ")

# Menampilkan variabel yang telah disimpan
print("\nData berhasil disimpan:")
print(f"Nama Makanan  : {nama_makanan}")
print(f"Nama Karakter : {nama_karakter}")
print(f"Kata Sifat    : {kata_sifat}")

# Menggabungkan ketiga variabel menjadi nama resmi toko
nama_toko = f"{nama_makanan.strip()} {nama_karakter.strip()} {kata_sifat.strip()}"

# Menampilkan hasil gabungan
print(f"Nama resmi toko adalah: {nama_toko}")

# Menyimpan jumlah modal masing-masing
modal_doraemon = 555000
modal_nobita = 333000
modal_shizuka = 222000

# Menampilkan modal yang telah disimpan
print(f"Modal Doraemon : Rp{modal_doraemon:,}")
print(f"Modal Nobita   : Rp{modal_nobita:,}")
print(f"Modal Shizuka  : Rp{modal_shizuka:,}")

# Menghitung total modal
total_modal = modal_doraemon + modal_nobita + modal_shizuka

# Menampilkan total modal
print(f"Total modal yang terkumpul: Rp{total_modal:,}")

# Menyimpan jumlah penjualan dan harga per buah
jumlah_dorayaki = 350
harga_dorayaki = 5000

# Menghitung total pendapatan
total_pendapatan = jumlah_dorayaki * harga_dorayaki

# Menampilkan hasil perhitungan
print(f"Jumlah Dorayaki Terjual : {jumlah_dorayaki} buah")
print(f"Harga per Dorayaki      : Rp{harga_dorayaki:,}")
print(f"Total Pendapatan Toko   : Rp{total_pendapatan:,}")

# Menghitung keuntungan (Total Pendapatan - Total Modal)
keuntungan = total_pendapatan - total_modal

# Menampilkan hasil keuntungan
print(f"Total Pendapatan       : Rp{total_pendapatan:,}")
print(f"Total Modal Awal       : Rp{total_modal:,}")
print(f"Keuntungan Bulan Pertama: Rp{keuntungan:,}")

# Perbaikan Kode menggunakan f-string (Sangat disarankan)
print(f"Keuntungan Toko Dorayaki adalah: Rp{keuntungan:,}")

# Alternatif lain menggunakan konversi tipe data str()
# print("Keuntungan Toko Dorayaki adalah: Rp" + str(keuntungan))